
server:
  port: 10033
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 114.55.39.2
    virtual-host: /java1907
    username: java1907
    password: 123
