server:
  port: 8848
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DialogD/config-server.git
  rabbitmq:
    host: 114.55.39.2
    virtual-host: /java1907
    username: java1907
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"